In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [16]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [17]:
dataset = pd.read_csv("/content/drive/MyDrive/Data.csv")
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [18]:
print(dataset.values)

[['France' 44.0 72000.0 'No']
 ['Spain' 27.0 48000.0 'Yes']
 ['Germany' 30.0 54000.0 'No']
 ['Spain' 38.0 61000.0 'No']
 ['Germany' 40.0 nan 'Yes']
 ['France' 35.0 58000.0 'Yes']
 ['Spain' nan 52000.0 'No']
 ['France' 48.0 79000.0 'Yes']
 ['Germany' 50.0 83000.0 'No']
 ['France' 37.0 67000.0 'Yes']]


In [19]:
print(dataset.iloc)

In [20]:
values = dataset.values

In [21]:
print(values[0][0])

France


In [22]:
print(values[:, 0 : 3])

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [23]:
print(dataset.iloc[0])

Country       France
Age             44.0
Salary       72000.0
Purchased         No
Name: 0, dtype: object


In [24]:
x = dataset.iloc[:, : -1]
print(x)

   Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  35.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0


In [25]:
y = dataset.iloc[:, -1].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [26]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(x.iloc[:, 1:])
x.iloc[:, 1:] = imputer.transform(x.iloc[:, 1:])
print(x.iloc[:, 1:])

         Age        Salary
0  44.000000  72000.000000
1  27.000000  48000.000000
2  30.000000  54000.000000
3  38.000000  61000.000000
4  40.000000  63777.777778
5  35.000000  58000.000000
6  38.777778  52000.000000
7  48.000000  79000.000000
8  50.000000  83000.000000
9  37.000000  67000.000000


In [27]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [36]:
ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')
x = np.array(ct.fit_transform(x))

In [35]:
from sklearn.preprocessing import LabelEncoder

In [37]:
le = LabelEncoder()
y = le.fit_transform(y)

In [39]:
print(x)
print(y)

[[1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.40000000e+01 7.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 2.70000000e+01 4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.80000000e+01 6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [1.000000

In [40]:
from sklearn.model_selection import train_test_split
xTrain, xTest, yTrain, yTest = train_test_split(x, y, test_size = 0.2)

In [41]:
print(xTrain)

[[0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 3.87777778e+01 5.20000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 4.00000000e+01 6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 3.70000000e+01 6.70000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 3.50000000e+01 5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  0.00000000e+00 4.80000000e+01 7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 5.00000000e+01 8.30000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  0.00000000e+00 3.00000000e+01 5.40000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 0.00000000e+00
  1.00000000e+00 2.70000000e+01 4.80000000e+04]]


In [42]:
print(xTest)

[[0.0e+00 1.0e+00 0.0e+00 0.0e+00 1.0e+00 3.8e+01 6.1e+04]
 [1.0e+00 0.0e+00 1.0e+00 0.0e+00 0.0e+00 4.4e+01 7.2e+04]]


In [43]:
print(yTrain)

[0 1 1 1 1 0 0 1]


In [44]:
print(print(yTest))

[0 0]
None


In [45]:
from sklearn.preprocessing import StandardScaler

In [46]:
scaler = StandardScaler()

In [47]:
xTrain[:, 3:] = scaler.fit_transform(xTrain[:, 3:])
xTest[:, 3:] = scaler.transform(xTest[:, 3:])

In [49]:
print(xTrain)
print(xTest)

[[ 0.          1.          0.         -0.77459667  1.73205081  0.07463934
  -0.93599577]
 [ 0.          1.          0.          1.29099445 -0.57735027  0.23884588
   0.05740149]
 [ 1.          0.          1.         -0.77459667 -0.57735027 -0.16420654
   0.32917999]
 [ 1.          0.          1.         -0.77459667 -0.57735027 -0.43290816
  -0.42992546]
 [ 1.          0.          1.         -0.77459667 -0.57735027  1.31365233
   1.34132059]
 [ 0.          1.          0.          1.29099445 -0.57735027  1.58235395
   1.67870079]
 [ 0.          1.          0.          1.29099445 -0.57735027 -1.10466219
  -0.76730567]
 [ 0.          1.          0.         -0.77459667  1.73205081 -1.50771461
  -1.27337597]]
[[ 0.          1.          0.         -0.77459667  1.73205081 -0.02985573
  -0.17689031]
 [ 1.          0.          1.         -0.77459667 -0.57735027  0.77624911
   0.75090524]]


In [59]:
from sklearn.neighbors import KNeighborsClassifier
kNN = KNeighborsClassifier(n_neighbors = 1)
print(kNN)

KNeighborsClassifier(n_neighbors=1)


In [60]:
kNN.fit(xTrain, yTrain)

KNeighborsClassifier(n_neighbors=1)

In [65]:
accuracy = kNN.predict(xTest)
print(accuracy)

[0 1]


In [66]:
np.mean(accuracy == yTest) * 100

50.0